Repository Instagram-clone-project-team/Instagram-clone, pull requests merged in 2023-09, with the labels that each got.

#6 feat - 정보 수정 API
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/dto/UpdatePasswordRequest.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/global/error/BusinessException.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/error/ErrorResponse.java
  src/main/java/com/project/Instagram/global/error/GlobalExceptionHandler.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
  src/main/java/com/project/Instagram/global/response/ResultResponse.java
Labels: feat

#9 faet - 로그인 기능
  build.gradle
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/dto/LoginRequest.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/RefreshToken.java
  src/main/java/com/project/Instagram/domain/member/service/UserDetailService.java
  src/main/java/com/project/Instagram/global/config/RedisConfig.java
  src/main/java/com/project/Instagram/global/config/SecurityConfig.java
  src/main/java/com/project/Instagram/global/jwt/CustomAuthorityUtils.java
  src/main/java/com/project/Instagram/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/project/Instagram/global/jwt/JwtToken.java
  src/main/java/com/project/Instagram/global/jwt/JwtTokenProvider.java
  src/main/java/com/project/Instagram/global/jwt/JwtVerificationFilter.java
  src/main/java/com/project/Instagram/global/jwt/RefreshTokenRedisRepository.java
Labels: feat

#5 feat - 회원가입 API 구현
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/dto/SendAuthEmailRequest.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/SignUpCode.java
  src/main/java/com/project/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/com/project/Instagram/domain/member/repository/SignUpCodeRedisRepository.java
  src/main/java/com/project/Instagram/domain/member/service/EmailAuthService.java
  src/main/java/com/project/Instagram/domain/member/service/EmailService.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/member/service/UserDetailService.java
  src/main/java/com/project/Instagram/global/config/SecurityConfig.java
  src/main/java/com/project/Instagram/global/entity/BaseTimeEntity.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
  src/main/java/com/project/Instagram/global/response/ResultResponse.java
Labels: feat

#7 feat - 로그아웃 / SecurityUtil
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/dto/SendAuthEmailRequest.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/member/service/RefreshTokenService.java
  src/main/java/com/project/Instagram/domain/member/service/UserDetailService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/project/Instagram/global/jwt/JwtVerificationFilter.java
  src/main/java/com/project/Instagram/global/jwt/RefreshTokenRedisRepository.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
  src/main/java/com/project/Instagram/global/util/SecurityUtil.java
Labels: feat

#10 refactor - security 수정
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/dto/ResetPasswordRequest.java
  src/main/java/com/project/Instagram/domain/member/dto/SendPasswordEmailRequest.java
  src/main/java/com/project/Instagram/domain/member/dto/UpdateAccountRequest.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/RefreshToken.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/global/config/SecurityConfig.java
  src/main/java/com/project/Instagram/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/project/Instagram/global/jwt/JwtTokenProvider.java
  src/main/java/com/project/Instagram/global/jwt/JwtVerificationFilter.java
Labels: refactor

#12 init - post 기본 설정
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: init

#11 feat 회원조회및탈퇴
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/Profile.java
  src/main/java/com/project/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/global/entity/BaseTimeEntity.java
  src/main/java/com/project/Instagram/global/entity/PageInfo.java
  src/main/java/com/project/Instagram/global/entity/PageListResponse.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: feat

#21 refactor-권한 테이블 분리 및 enum으로 적용
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/member/service/UserDetailService.java
  src/main/java/com/project/Instagram/global/jwt/CustomAuthorityUtils.java
  src/main/java/com/project/Instagram/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/project/Instagram/global/jwt/JwtVerificationFilter.java
Labels: refactor
