Repository Instagram-clone-project-team/Instagram-clone, pull requests merged in 2023-10, with the labels that each got.

#23 refactor-role 타입 재설정
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/MemberRole.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/member/service/RefreshTokenService.java
  src/main/java/com/project/Instagram/global/config/SecurityConfig.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/jwt/CustomAuthorityUtils.java
  src/main/java/com/project/Instagram/global/jwt/JwtVerificationFilter.java
Labels: refactor

#16 feat-게시물 삭제, 수정
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/dto/EditPostRequest.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: feat

#18 feat-S3 image uploader 기능 구현
  build.gradle
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/dto/PostCreateRequest.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/config/S3Config.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
  src/main/java/com/project/Instagram/global/util/S3Uploader.java
Labels: feat

#13 feat 토큰재발급 기능
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/member/service/RefreshTokenService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: feat

#19 feat - 게시물 조회
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/dto/PostResponse.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
  src/main/java/com/project/Instagram/global/util/SecurityUtil.java
Labels: feat

#26 refactor-기본 프로필 이미지
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/Profile.java
Labels: refactor

#28 refactor-게시물 수정 이미지
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/dto/EditPostRequest.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: refactor

#34 refactor- 조회 이미지추가
  src/main/java/com/project/Instagram/domain/post/dto/PostResponse.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: refactor

#39 Refactor - 좋아요수추가
  src/main/java/com/project/Instagram/domain/member/dto/LikesMemberResponseDto.java
  src/main/java/com/project/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/controller/PostLikeController.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/entity/PostLike.java
  src/main/java/com/project/Instagram/domain/post/repository/PostLikeRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostLikeService.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: refactor

#30 feat-팔로우 구현
  build.gradle
  src/main/java/com/project/Instagram/domain/follow/controller/FollowController.java
  src/main/java/com/project/Instagram/domain/follow/dto/FollowerDto.java
  src/main/java/com/project/Instagram/domain/follow/entity/Follow.java
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepository.java
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepositoryQuerydsl.java
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepositoryQuerydslImpl.java
  src/main/java/com/project/Instagram/domain/follow/service/FollowService.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/Profile.java
  src/main/java/com/project/Instagram/global/config/QuerydslConfig.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: feat

#32 feat-로그인 유저가 팔로우한 유저 게시물 조회 API
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepository.java
  src/main/java/com/project/Instagram/domain/follow/service/FollowService.java
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: feat

#33 Feat - 해시태그 구현
  src/main/java/com/project/Instagram/domain/post/entity/Hashtag.java
  src/main/java/com/project/Instagram/domain/post/entity/PostHashtag.java
  src/main/java/com/project/Instagram/domain/post/repository/HashtagRepository.java
  src/main/java/com/project/Instagram/domain/post/repository/PostHashtagRepository.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/HashtagService.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: feat

#37 feat 댓글 도메인
  src/main/java/com/project/Instagram/domain/comment/controller/CommentController.java
  src/main/java/com/project/Instagram/domain/comment/dto/CommentRequest.java
  src/main/java/com/project/Instagram/domain/comment/dto/CommentResponse.java
  src/main/java/com/project/Instagram/domain/comment/dto/SimpleComment.java
  src/main/java/com/project/Instagram/domain/comment/entity/Comment.java
  src/main/java/com/project/Instagram/domain/comment/repository/CommentRepository.java
  src/main/java/com/project/Instagram/domain/comment/service/CommentService.java
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/member/entity/Member.java
  src/main/java/com/project/Instagram/domain/member/entity/Profile.java
  src/main/java/com/project/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/config/SecurityConfig.java
  src/main/java/com/project/Instagram/global/entity/BaseTimeEntity.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: feat

#41 refactor- 게시물 이미지수정
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: refactor

#42 refactor-컨벤션/로그인팔로우게시물API
  src/main/java/com/project/Instagram/domain/follow/controller/FollowController.java
  src/main/java/com/project/Instagram/domain/follow/service/FollowService.java
  src/main/java/com/project/Instagram/domain/member/controller/MemberController.java
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/controller/PostLikeController.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: refactor

#43 refactor-gradle설정변경
  build.gradle
  src/main/java/com/project/Instagram/domain/member/dto/LikesMemberResponseDto.java
Labels: refactor

#47 feat mention service
  src/main/java/com/project/Instagram/domain/comment/service/CommentService.java
  src/main/java/com/project/Instagram/domain/mention/service/MentionService.java
  src/main/java/com/project/Instagram/domain/post/repository/PostRepository.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: feat

#48 refactor-로그인 확인 작업 수정
  src/main/java/com/project/Instagram/domain/alarm/entity/Alarm.java
  src/main/java/com/project/Instagram/domain/alarm/service/AlarmService.java
  src/main/java/com/project/Instagram/domain/follow/service/FollowService.java
  src/main/java/com/project/Instagram/domain/post/service/PostLikeService.java
Labels: refactor

#51 refactor mention기능 수정시 로직 추가
  src/main/java/com/project/Instagram/domain/comment/service/CommentService.java
  src/main/java/com/project/Instagram/domain/mention/service/MentionService.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: refactor

#50 refactor- follow 도메인 deletedAt 수정 / 팔로우한 게시물 조회
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepository.java
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepositoryQuerydsl.java
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepositoryQuerydslImpl.java
  src/main/java/com/project/Instagram/domain/follow/service/FollowService.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/post/controller/PostController.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: refactor

#53 Refactor- 좋아요, 게시글 해시태그
  src/main/java/com/project/Instagram/domain/alarm/entity/Alarm.java
  src/main/java/com/project/Instagram/domain/comment/controller/CommentLikeController.java
  src/main/java/com/project/Instagram/domain/comment/entity/CommentLike.java
  src/main/java/com/project/Instagram/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/project/Instagram/domain/comment/service/CommentLikeService.java
  src/main/java/com/project/Instagram/domain/post/entity/PostHashtag.java
  src/main/java/com/project/Instagram/domain/post/repository/PostLikeRepository.java
  src/main/java/com/project/Instagram/domain/post/service/HashtagService.java
  src/main/java/com/project/Instagram/domain/post/service/PostLikeService.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/response/ResultCode.java
Labels: refactor

#54 Refactor 댓글해시태그
  src/main/java/com/project/Instagram/domain/comment/entity/CommentHashtag.java
  src/main/java/com/project/Instagram/domain/comment/repository/CommentHashtagRepository.java
  src/main/java/com/project/Instagram/domain/comment/service/CommentService.java
  src/main/java/com/project/Instagram/domain/post/service/HashtagService.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
Labels: refactor

#52 feat-알람 전체 조회
  src/main/java/com/project/Instagram/domain/alarm/controller/AlarmController.java
  src/main/java/com/project/Instagram/domain/alarm/dto/AlarmContentDto.java
  src/main/java/com/project/Instagram/domain/alarm/dto/AlarmFollowDto.java
  src/main/java/com/project/Instagram/domain/alarm/dto/AlarmType.java
  src/main/java/com/project/Instagram/domain/alarm/entity/Alarm.java
  src/main/java/com/project/Instagram/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/project/Instagram/domain/alarm/repository/AlarmRepositoryJdbc.java
  src/main/java/com/project/Instagram/domain/alarm/repository/AlarmRepositoryJdbcImpl.java
  src/main/java/com/project/Instagram/domain/alarm/repository/AlarmRepositoryQuerydsl.java
  src/main/java/com/project/Instagram/domain/alarm/repository/AlarmRepositoryQuerydslImpl.java
  src/main/java/com/project/Instagram/domain/alarm/service/AlarmService.java
  src/main/java/com/project/Instagram/domain/comment/service/CommentService.java
  src/main/java/com/project/Instagram/domain/follow/repository/FollowRepository.java
  src/main/java/com/project/Instagram/domain/member/repository/MemberRepository.java
  src/main/java/com/project/Instagram/domain/member/service/MemberService.java
  src/main/java/com/project/Instagram/domain/mention/service/MentionService.java
  src/main/java/com/project/Instagram/domain/post/service/HashtagService.java
  src/main/java/com/project/Instagram/domain/post/service/PostLikeService.java
  src/main/java/com/project/Instagram/domain/post/service/PostService.java
  src/main/java/com/project/Instagram/global/error/ErrorCode.java
  src/main/java/com/project/Instagram/global/util/StringExtractUtil.java
Labels: feat

#58 init - search 도메인 기본 틀
  src/main/java/com/project/Instagram/domain/comment/entity/Comment.java
  src/main/java/com/project/Instagram/domain/comment/entity/CommentHashtag.java
  src/main/java/com/project/Instagram/domain/comment/entity/CommentLike.java
  src/main/java/com/project/Instagram/domain/post/entity/Hashtag.java
  src/main/java/com/project/Instagram/domain/post/entity/Post.java
  src/main/java/com/project/Instagram/domain/search/controller/SearchController.java
  src/main/java/com/project/Instagram/domain/search/dto/SearchDto.java
  src/main/java/com/project/Instagram/domain/search/entity/RecentSearch.java
  src/main/java/com/project/Instagram/domain/search/entity/Search.java
  src/main/java/com/project/Instagram/domain/search/entity/SearchHashtag.java
  src/main/java/com/project/Instagram/domain/search/entity/SearchMember.java
  src/main/java/com/project/Instagram/domain/search/repository/RecentSearchRepository.java
  src/main/java/com/project/Instagram/domain/search/repository/RecentSearchRepositoryQuerydsl.java
  src/main/java/com/project/Instagram/domain/search/repository/SearchHashtagRepository.java
  src/main/java/com/project/Instagram/domain/search/repository/SearchMemberRepository.java
  src/main/java/com/project/Instagram/domain/search/repository/SearchRepository.java
  src/main/java/com/project/Instagram/domain/search/repository/SearchRepositoryQuerydsl.java
  src/main/java/com/project/Instagram/domain/search/service/SearchService.java
Labels: init
